### ISSUE TITLE
Pacman-mirrors its broken

### ISSUE THREAD

**Issue by bn0785ac** [manjaro/packages-core#114]
Version: 4.8.0-1

command: pacman-mirrors -i

log
```

Traceback (most recent call last):
  File "/usr/bin/pacman-mirrors", line 57, in <module>
    pm.run()
  File "/usr/lib/python3.6/site-packages/pacman_mirrors/pacman_mirrors.py", line 908, in run
    self.build_interactive_mirror_list()
  File "/usr/lib/python3.6/site-packages/pacman_mirrors/pacman_mirrors.py", line 605, in build_interactive_mirror_list
    self.default)
  File "/usr/lib/python3.6/site-packages/pacman_mirrors/dialogs/graphicalui.py", line 160, in run
    window = GraphicalUI(server_list, random, default)
  File "/usr/lib/python3.6/site-packages/pacman_mirrors/dialogs/graphicalui.py", line 54, in __init__
    "{}h {}m".format(server["last_sync"][:2],
TypeError: 'int' object is not subscriptable

```

**Comment by oberon2007** [comment]
@fhdk

**Comment by fhdk** [comment]
https://github.com/manjaro/pacman-mirrors/issues/123

**Comment by fhdk** [comment]
Fixed in 4.8.3

**Comment by jonathonf** [comment]
^ GitHub hint :wink:

**Comment by fhdk** [comment]
:question:

**Comment by fhdk** [comment]
Do you want me to push it to x32?

**Comment by jonathonf** [comment]
Sorry, no - it was a hint that it's possible to assign people to issues directly as well as mentioning them in comments. :)

If the packaging files are in the GitHub repos they will be built and uploaded as and when I do builds - no need to worry about pushing to x32 (unless it's a critical fix and you want to :wink:).

**Comment by fhdk** [comment]
Oh - I knew that :sunglasses:
