### ISSUE TITLE
cannot push to pkgs-core repo

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-core#123]
Even after using a fresh clone of the repo I get this error when trying to `git push`
```
$ git push
Password for 'https://oberon2007@github.com': 
Counting objects: 4, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 405 bytes | 405.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
remote: /data/github/releases/deploy-b/vendor/gems/2.4.2/ruby/2.4.0/gems/statsd-ruby-0.3.0.github.3.38.gd478cc7/lib/github/statsd.rb:23:in `ip': getaddrinfo: Name or service not known (SocketError)
remote: 	from /data/github/releases/deploy-b/vendor/gems/2.4.2/ruby/2.4.0/gems/statsd-ruby-0.3.0.github.3.38.gd478cc7/lib/github/statsd.rb:23:in `initialize'
remote: 	from /data/github/releases/deploy-b/vendor/gems/2.4.2/ruby/2.4.0/gems/statsd-ruby-0.3.0.github.3.38.gd478cc7/lib/github/statsd.rb:106:in `new'
remote: 	from /data/github/releases/deploy-b/vendor/gems/2.4.2/ruby/2.4.0/gems/statsd-ruby-0.3.0.github.3.38.gd478cc7/lib/github/statsd.rb:106:in `add_shard'
remote: 	from /data/github/releases/deploy-b/lib/github/config/stats.rb:33:in `block in create_statsd'
remote: 	from /data/github/releases/deploy-b/lib/github/config/stats.rb:33:in `each'
remote: 	from /data/github/releases/deploy-b/lib/github/config/stats.rb:33:in `create_statsd'
remote: 	from /data/github/releases/deploy-b/lib/github/config/stats.rb:20:in `stats'
remote: 	from /data/github/releases/deploy-b/lib/github/config/stats.rb:244:in `<module:GitHub>'
remote: 	from /data/github/releases/deploy-b/lib/github/config/stats.rb:12:in `<top (required)>'
remote: 	from /data/github/releases/deploy-b/config/basic.rb:66:in `require'
remote: 	from /data/github/releases/deploy-b/config/basic.rb:66:in `require'
remote: 	from /data/github/releases/deploy-b/lib/github/logger.rb:3:in `<top (required)>'
remote: 	from /data/github/releases/deploy-b/config/basic.rb:66:in `require'
remote: 	from /data/github/releases/deploy-b/config/basic.rb:66:in `require'
remote: 	from /data/github/releases/deploy-b/lib/github.rb:137:in `<module:GitHub>'
remote: 	from /data/github/releases/deploy-b/lib/github.rb:20:in `<top (required)>'
remote: 	from /data/github/releases/deploy-b/config/basic.rb:66:in `require'
remote: 	from /data/github/releases/deploy-b/config/basic.rb:66:in `require'
remote: 	from /data/github/releases/deploy-b/config/basic.rb:230:in `<top (required)>'
remote: 	from /data/github/releases/deploy-b/vendor/ruby/44c51a28900fc53699489c87289294b79ee365d3/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
remote: 	from /data/github/releases/deploy-b/vendor/ruby/44c51a28900fc53699489c87289294b79ee365d3/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
To https://github.com/manjaro/packages-core.git
 ! [remote rejected]   master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://oberon2007@github.com/manjaro/packages-core.git'
```
ideas, @philmmanjaro . Should I report this to github support?

**Comment by oberon2007** [comment]
After committing my original failed commit online with the web-interface and making another fresh clone I was now able to push a test commit.
But another strange thing is occurring now: `git add .` doesn't seem to work anymore and I have to specify the file to add explicitly now ??

**Comment by oberon2007** [comment]
Ok. weird stuff! Now everything is magically working again, including `git add .`
I have rebased the useless commits :stuck_out_tongue_winking_eye:
