### ISSUE TITLE
[pacman-mirrors] incompatible with manjaro-tools?

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-core#88]
I just built an ISO against unstable branch and the install ends up with no mirrorlist:
$ sudo pacman -Syu
error: config file /etc/pacman.d/mirrorlist could not be read: No such file or directory
Looks like something has been changed with the latest updates that either needs to be fixed or addressed in the tools!?
@fhdk @philmmanjaro

**Comment by oberon2007** [comment]
From the buildlog:
```
 --> Setting mirrorlist branch: unstable
sed: can't read /var/lib/manjaro-tools/buildiso/cinnamon/x86_64/rootfs/etc/pacman.d/mirrorlist: No such file or directory
```

**Comment by oberon2007** [comment]
From my own installed system:
```
$ pacman -Qo /etc/pacman.d/mirrorlist 
error: No package owns /etc/pacman.d/mirrorlist
```
So seems the file is simply no longer installed?

**Comment by Kirek** [comment]
My guess is that the install hook for pacman-mirrors needs to be updated (-y was deprecated I think)
https://github.com/manjaro/packages-core/blob/master/pacman-mirrors/pacman-mirrors-install.script

**Comment by oberon2007** [comment]
Right, spot on! Option `-y` appears to no longer exist 😉

**Comment by oberon2007** [comment]
@fhdk looking at the PKGBUILD I see that some pkgrel have been built without the changes having been committed - so I am not sure if there have been other changes - please have a look and rebuild the required pkgrel 6 for us, thanks!

**Comment by fhdk** [comment]
Bernhard Landauer skrev den 2017-11-08 14:58:
> I just built an ISO against unstable branch and the install ends up
> with no mirrorlist:
> $ sudo pacman -Syu
> error: config file /etc/pacman.d/mirrorlist could not be read: No such
> file or directory
> Looks like something has been changed with the latest updates that
> either needs to be fixed or addressed in the tools!?
> @fhdk [1] @philmmanjaro [2]

For the last two months deprecation messages has been printed for

-y - with 4.4 -y is removed
-g - has been changed so it has same functionality as -f and the number 
is now optional.

**Comment by fhdk** [comment]
Bernhard Landauer skrev den 2017-11-08 15:24:
> @fhdk [1] looking at the PKGBUILD I see that some pkgrel have been
> built without the changes having been committed - so I am not sure if
> there have been other changes - please have a look and rebuild the
> required pkgrel 6 for us, thanks!
> 

Has been done.

**Comment by oberon2007** [comment]
> For the last two months deprecation messages has been printed for

That's fine. You just forgot to remove the deprecated flag in the install script of the package [itself](https://github.com/manjaro/packages-core/commit/d5a04bd2c2b943f6dae5a14f2884255eda999113)! 😉

**Comment by oberon2007** [comment]
There is still a problem with the hook:
```
( 4/10) Configuring pacman-mirrors ...
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1392, in connect
    super().connect()
  File "/usr/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pacman-mirrors", line 56, in <module>
    pm.run()
  File "/usr/lib/python3.6/site-packages/pacman_mirrors/pacman_mirrors.py", line 867, in run
    self.network = httpfn.inet_conn_check()
  File "/usr/lib/python3.6/site-packages/pacman_mirrors/functions/httpfn.py", line 170, in inet_conn_check
    data = urlopen(host, timeout=maxwait)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
hint: use `pacman-mirrors` to generate and update your pacman mirrorlist.
```

**Comment by Kirek** [comment]
Basically when you bootstraping the image it doesnt have internet access and pacman-mirrors now doesn't handle this well it seems.

**Comment by Kirek** [comment]
Basically when you are bootstraping the image it doesnt have internet access and pacman-mirrors now doesn't handle this well it seems.

**Comment by philmmanjaro** [comment]
We have to find a proper solution for this one. Therefore an offline option is needed. @fhdk was this even tested?

**Comment by fhdk** [comment]
I know why - it is a () in the inet check

**Comment by philmmanjaro** [comment]
Ok, so there is a solution to it :smiley:

**Comment by fhdk** [comment]
It was tested - don't know why it fails now

**Comment by fhdk** [comment]
pkgrel=8 on its way

**Comment by fhdk** [comment]
> That's fine. You just forgot to remove the deprecated flag in the install script of the package 
I am deeply sorry this mess

**Comment by fhdk** [comment]
Should have been
```
        # noinspection PyBroadException
        try:
            data = urlopen(host, timeout=maxwait)
            break
        except:
            pass
```
By my mistake I did
```
        # noinspection PyBroadException
        try:
            data = urlopen(host, timeout=maxwait)
            break
        except ():
            pass
```

**Comment by oberon2007** [comment]
Not to worry! It's fixed now, thank you! 👍 
```
( 4/10) Configuring pacman-mirrors ...
.: WARNING Internet connection appears to be down
.: INFO Mirror ranking is not available
.: INFO Mirror list is generated using random method
.: INFO Writing mirror list
   United_States   : https://mirror.math.princeton.edu/pub/manjaro/stable
   Sweden          : https://ftp.lysator.liu.se/pub/manjaro/stable
   Netherlands     : https://ftp.nluug.nl/pub/os/Linux/distr/manjaro/stable
   Germany         : http://ftp.rz.tu-bs.de/pub/mirror/manjaro.org/repos/stable
   Indonesia       : http://kambing.ui.ac.id/manjaro/stable
   Sweden          : https://mirror.zetup.net/manjaro/stable
   Colombia        : http://mirror.edatel.net.co/manjaro/stable
   Italy           : https://ba.mirror.garr.it/mirrors/manjaro/stable
   Austria         : http://mirror.inode.at/manjaro/stable
   Bulgaria        : http://manjaro.telecoms.bg/stable
   Turkey          : http://ftp.linux.org.tr/manjaro/stable
   United_Kingdom  : http://repo.manjaro.org.uk/stable
   United_States   : https://mirrors.ocf.berkeley.edu/manjaro/stable
   China           : https://mirrors.zju.edu.cn/manjaro/stable
   Australia       : http://mirror.ventraip.net.au/Manjaro/stable
   Canada          : https://osmirror.org/manjaro/stable
   Italy           : https://ct.mirror.garr.it/mirrors/manjaro/stable
   Denmark         : https://www.uex.dk/public/manjaro/stable
   Romania         : http://mirrors.serverhost.ro/manjaro/packages/stable
   Bulgaria        : https://mirrors.netix.net/manjaro/stable
   Germany         : http://mirror.ragenetwork.de/manjaro/stable
   Belarus         : http://mirror.datacenter.by/pub/mirrors/manjaro/stable
   United_Kingdom  : http://mirror.catn.com/pub/manjaro/stable
   Germany         : https://mirror.netcologne.de/manjaro/stable
   Germany         : http://ftp.tu-chemnitz.de/pub/linux/manjaro/stable
   Belgium         : ftp://ftp.belnet.be/mirrors/manjaro/stable
   Germany         : https://repo.stdout.net/manjaro/stable
   Costa_Rica      : https://mirrors.ucr.ac.cr/manjaro/stable
   Netherlands     : https://manjaro.mirror.wearetriple.com/stable
   Japan           : http://ftp.tsukuba.wide.ad.jp/Linux/manjaro/stable
   United_States   : https://mirror.clarkson.edu/manjaro/stable
   South_Africa    : http://mirror.is.co.za/mirrors/manjaro.org/stable
   Germany         : https://mirror.netzspielplatz.de/manjaro/packages/stable
   United_Kingdom  : https://www.mirrorservice.org/sites/repo.manjaro.org/repos/
   France          : http://mirror.lignux.com/manjaro/stable
   France          : http://ftp.free.org/mirrors/repo.manjaro.org/repos/stable
   Australia       : http://manjaro.mirror.serversaustralia.com.au/stable
   Belgium         : http://ftp.belnet.be/manjaro/stable
   Chile           : http://manjaro.dcc.uchile.cl/stable
   France          : http://kibo.remi.lu/stable
   Russia          : https://mirror.yandex.ru/mirrors/manjaro/stable
   China           : https://mirrors.ustc.edu.cn/manjaro/stable
   France          : https://fr.mirror.babylon.network/manjaro/stable
   Philippines     : http://mirror.rise.ph/manjaro/stable
   China           : http://mirrors.tuna.tsinghua.edu.cn/manjaro/stable
   Belgium         : https://manjaro.cu.be/stable
   Germany         : https://manjaro-mirror-a.alpix.eu/stable
   Taiwan          : http://free.nchc.org.tw/manjaro/stable
   United_Kingdom  : http://manjaro.mirrors.uk2.net/stable
   Bulgaria        : https://manjaro.ipacct.com/manjaro/stable
   Germany         : https://ftp.halifax.rwth-aachen.de/manjaro/stable
   United_States   : http://mirror.dacentec.com/manjaro/stable
   Italy           : https://manjaro.mirror.garr.it/mirrors/manjaro/stable
   Germany         : https://mirror.alpix.eu/manjaro/stable
   Germany         : http://babyname.tips/mirrors/manjaro/stable
   Hungary         : http://mirror.infotronik.hu/mirrors/pub/manjaro/stable
   United_States   : http://distro.ibiblio.org/manjaro/stable
   Romania         : http://ftp.lug.ro/manjaro/stable
   Australia       : http://manjaro.melbourneitmirror.net/stable
   Hong_Kong       : http://ftp.cuhk.edu.hk/pub/Linux/manjaro/stable
   Portugal        : http://manjaro.barata.pt/stable
   Ireland         : https://ftp.heanet.ie/mirrors/manjaro/stable
   Netherlands     : http://ftp.snt.utwente.nl/pub/linux/manjaro/stable
   Portugal        : http://ftp.dei.uc.pt/pub/linux/manjaro/stable
   United_States   : http://mirror.solarvps.com/manjaro/stable
   Germany         : https://repo.rhindon.net/manjaro/stable
   Indonesia       : http://kartolo.sby.datautama.net.id/manjaro/stable
   Spain           : http://ftp.caliu.cat/manjaro/stable
   Japan           : http://ftp.riken.jp/Linux/manjaro/stable
   Czech           : https://mirror.dkm.cz/manjaro/stable
   Russia          : http://mirror.truenetwork.ru/manjaro/stable
   Ecuador         : https://mirror.espoch.edu.ec/manjaro/stable
   Ecuador         : https://mirror.cedia.org.ec/manjaro/stable
   Netherlands     : https://mirror.koddos.net/manjaro/stable
   Denmark         : https://mirrors.dotsrc.org/manjaro/stable
   Singapore       : https://download.nus.edu.sg/mirror/manjaro/stable
   Netherlands     : https://nl.mirror.babylon.network/manjaro/stable
.: INFO Mirror list generated and saved to: /etc/pacman.d/mirrorlist
hint: use `pacman-mirrors` to generate and update your pacman mirrorlist.
```
